# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-20 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django_boto.s3.storage


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='photo',
            field=models.ImageField(storage=django_boto.s3.storage.S3Storage(), upload_to=''),
        ),
    ]
