# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-20 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0006_auto_20170620_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='photo',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=''),
        ),
    ]
