# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-20 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0007_auto_20170620_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='photo',
            field=models.FileField(upload_to='gigs'),
        ),
    ]
